### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by FatGrizzly** [digitallysavvy/agora-web-broadcast-demo#4]
Hello bruh, I am small student I saw ur blog and sadly couldn’t understand anything. I downloaded all the files from GitHub and added my APPID and hosted it using ngrok and xampp but still. how should I be a broadcaster please explain….. I cant understand,please help me so that I could learn

    contact me through mailto:admin@soundarahari.tk

**Comment by digitallysavvy** [comment]
If you are using xampp, assuming the project is in a folder called `agora-web-broadcast-demo` in the `htdocs` directory, then you can access the pages with the following urls:

- broadcast host: `localhost/agora-web-broadcast-demo/agora-broadcast-client.html`
- audience: `localhost/agora-web-broadcast-demo/`

**Comment by FatGrizzly** [comment]
Really Thank you bruh
